apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.general.metadata.name | quote }}
  name: {{ .Values.general.metadata.name | quote }}
  namespace: {{ .Values.general.metadata.namespace | quote }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.general.metadata.name | quote }}
  type: ClusterIP
