apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.general.metadata.name | quote }}
  name: {{ .Values.general.metadata.name | quote }}
  namespace: {{ .Values.general.metadata.namespace | quote }}
spec:
  ports:
  - port: {{ .Values.general.port }}
    protocol: TCP
    targetPort: {{ .Values.general.port }}
  selector:
    app: {{ .Values.general.metadata.name | quote }}
  type: NodePort
