apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: cert-manager
spec:
  acme:
    email: martin.beranek@shipmonk.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "trustsoft.beranm.cz"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z04333023IJ7G2JUEJXMX